version: '3.8'
services:
  # Service 1: Ứng dụng Node.js của chúng ta
  app:
    build: .
    ports:
      - "1995:3000"
    restart: on-failure
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo-db # Đợi DB chạy rồi App mới chạy

  # Service 2: Database MongoDB
  mongo-db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db # Lưu dữ liệu ra ngoài để không mất khi tắt container

# Khai báo volume để lưu dữ liệu bền vững
volumes:
  mongo-data:
